In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np

In [22]:
def get_review(newsoup):
    try:
        review = newsoup.findAll('h2', attrs={'class':'text_header'})
        review_value=review[i].text.replace('"' , " ")
        review_string = review_value.strip()
    except AttributeError:
        review_string = " "
    return review_string
def get_names(newsoup):
    try:
        names = newsoup.findAll('span' , attrs={'itemprop' : 'name'})
        names_value=names[i].text
        names_string= names_value.strip()
    except AttributeError:
        names_string = " "
    return names_string
def get_dates(newsoup):
    try:
        dates = newsoup.findAll('time' , attrs={'itemprop':'datePublished'})
        dates_value=dates[i].text
        dates_string= dates_value.strip()
    except AttributeError:
        dates_string = " "
    return dates_string
def get_rating(newsoup):
    try:
        rates = newsoup.findAll('div' , attrs={'itemprop':'reviewRating'})
        
        rating_value=rates[i].text
        rating_string=rating_value.strip() + ' -  rating'
    except:
        rating_string=" "
    return rating_string
def get_route(newsoup):
    try:
       
        route = soup.find_all('td',class_='review-rating-header route')
        all_routedata = [r.find_next('td') for r in route]
        route_string = all_routedata[i].text
         
    except AttributeError:
        route_string = " "
    return route_string

In [23]:
if __name__ == '__main__':
    HEADERS = ({'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36','Accept-Language': 'en-US, en;q=0.5'})
    #url
    URL = "https://www.airlinequality.com/airline-reviews/british-airways/"
    webpage = requests.get(URL, headers=HEADERS)
    soup=BeautifulSoup(webpage.content, 'html.parser')
    names = soup.find_all('span', attrs={'itemprop': 'name'})
    names_list = []
    for name in names:
        names_list.append(name.text)             
    d = {'usernames':[], 'reviewdata':[],'traveldate':[],'ratings':[],'route':[]}
    for i in range(len(names_list)):
        d['usernames'].append(get_names(soup))
        d['reviewdata'].append(get_review(soup))
        d['traveldate'].append(get_dates(soup))
        d['ratings'].append(get_rating(soup))
        d['route'].append(get_route(soup))
       
    ba_df = pd.DataFrame.from_dict(d)
    ba_df.to_csv('airways.csv')

In [25]:
ba_df

,usernames,reviewdata,traveldate,ratings,route
0,Paul Mercer,spent two hours trying to make contact with BA,25th October 2024,1/10 - rating,Mexico City to London Heathrow
1,M Stansfield,using another airline for future travel,24th October 2024,1/10 - rating,Paris to Boston via London
2,Claude Cahn,oversold tickets on our flight,22nd October 2024,1/10 - rating,Geneva to London
3,Peter Mountford,“Appalling service”,14th October 2024,1/10 - rating,Johannesburg to London
4,Paul Mercer,“BA’s petty penny pinching ”,12th October 2024,6/10 - rating,London to Mexico City
5,N Bauer,“British arrogance with no manners”,12th October 2024,1/10 - rating,Berlin to London Heathrow
6,Jianping Wang,Terrible customer service,12th October 2024,2/10 - rating,London Heathrow to Philadelphia
7,T Kaz,“left much to be desired”,9th October 2024,1/10 - rating,Johannesburg to New York City via Heathrow
8,James Tapley,crew were all very friendly,8th October 2024,8/10 - rating,New York JFK to London Heathrow
9,James Wills,Simply not good enough,6th October 2024,4/10 - rating,Antalya to Gatwick